### ISSUE TITLE
VIPS dependency not getting picked up on production server

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#101]
The worker logs are filled w/ this:

```
Error: Please install one of the following libraries: vips (^7.32.1), imagemagick (^6.6.9)
```

What gives? VIPS should be installed from `./zh setup`.

Blocking issue for #89, #91.

**Comment by aseemk** [comment]
Simple test on any server:

```sh
$ cd /var/apps/zoomhub
$ node_modules/.bin/_coffee ./scripts/convert._coffee <id>
# where <id> is any known "queued" ID, e.g. `100` on staging
```

Unfortunately, the worker isn't working correctly on staging at the moment (#103), so can't test this on staging...

**Comment by kenperkins** [comment]
from a freshly provisioned test environment:

```
zoomhub@zoomhub-web-test-01-iad:/var/apps/zoomhub$ node_modules/.bin/_coffee ./scripts/convert._coffee 1002015-02-23T21:48:20.568Z [Worker] Processing content... id="100", url="http://e.i.uol.com.br/outros/0907/090731cielao1.jpg"
2015-02-23T21:48:20.570Z [Worker] Content already successfully processed. id="100"
2015-02-23T21:48:20.571Z [Worker] Finished processing content. id="100"
Content with ID 100 converted! Time taken: 4ms
```

**Comment by iangilman** [comment]
I don't see anything specific in our code for installing VIPS: 

https://github.com/zoomhub/zoomhub/search?utf8=%E2%9C%93&q=vips

Is the idea that we just automatically get it because of node-deepzoom-tools' dependencies? Why don't we just add it explicitly to our own, so we know it's taken care of? 

That said, looks like Ken has it working on a fresh environment, so maybe we go that way?

**Comment by aseemk** [comment]
Hey folks,

If you look at the second line of Ken's output, it says "Content already successfully processed" — which it shouldn't be, and I've filed as issue #103 — so it's not testing VIPS being present or not.

@iangilman: node-deepzoomtools doesn't include VIPS; VIPS has to be installed separately on the system as a pre-req. We do install it via Ansible as part of `./zh setup`:

https://github.com/zoomhub/zoomhub/blob/master/deployment/roles/vips/tasks/main.yml
https://github.com/zoomhub/zoomhub/blob/master/deployment/setup.yml#L12

And when I ssh into both production and staging, it *does* seem to be there:

```
$ vips --version
vips-7.36.6-Mon Oct 13 20:50:48 UTC 2014
```

So perhaps the issue is somewhere in node-deepzoomtools. Not sure though.

**Comment by kenperkins** [comment]
```
zoomhub@zoomhub-web-test-01-iad:~$ vips --version
vips-7.36.6-Mon Feb 23 20:44:45 UTC 2015
```

**Comment by gasi** [comment]
Didn’t have this problem while converting #89.
