### ISSUE TITLE
Move queued.dzi to CDN'ed Cloud Files

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#102]
Low-hanging fruit, and can easily be done manually through the UI.

We'd also then need to update our code to point to it. We already point to the CDN for OpenSeadragon UI imagery, so it should be pretty similar there.

One last bit is that we do need the DZI XML info locally (we call `DZIParser.parse` on it), so perhaps we keep the XML file checked in locally.

**Comment by gasi** [comment]
Done for v2: http://content.zoomhub.net/static/queued.dzi

**Comment by gasi** [comment]
Closing out old issues. Feel free to reopen if relevant.
