### ISSUE TITLE
Staging server behaves differently than production or local

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#103]
Really wonky — I uploaded the same kind of test data we use locally to staging, but its behavior is different, and in bafflingly opposite ways.

Uploaded these files, under `/var/data/zoomhub/content-by-id` (`cat` any of them to see the full data):
- `100.json`: `ready: false` (only change from what's checked-in to this repo)
- `100_U.json`: `ready: true` (unchanged from what's checked-in to this repo)
- `4rcn.json`: `ready: true` (unchanged from what's checked-in to this repo)
- `hdfm.json`: `ready: false` (only change from what's checked-in to this repo)

You can see two of these four are ready, two aren't.

What's baffling is that _three_ of the four show up as queued according to the website/API: while `100` and `hdfm` _should_, `100U` _also_ is:

http://staging.zoomhub.net/100U

But interestingly, it's _not_ showing up as queued from the API, i.e. `ready` is `true`, and a `dzi` is present, with a `url` — which is [what our embed code looks for](https://github.com/zoomhub/zoomhub/blob/c2a5ae6f47efd050f967fbce302e3de457e5bdb5/lib/embed._coffee#L31):

http://staging.zoomhub.net/v1/content/100U

Finally, when I try to run the worker on these guys to (re-)generate their DZIs, the worker thinks the opposite of this — it thinks that _all_ of these are already converted! E.g.:

```
zoomhub@zoomhub-web-staging-01-iad:/var/apps/zoomhub$ ./node_modules/.bin/_coffee ./scripts/convert._coffee 100
2015-02-23T15:29:45.424Z [Worker] Processing content... id="100", url="http://e.i.uol.com.br/outros/0907/090731cielao1.jpg"
2015-02-23T15:29:45.426Z [Worker] Content already successfully processed. id="100"
2015-02-23T15:29:45.426Z [Worker] Finished processing content. id="100"
Content with ID 100 converted! Time taken: 4ms
```

What the heck is going on?

**Comment by aseemk** [comment]
Given that staging is running the same code as production and local, the problem is likely in the config. Indeed, our Ansible deployment isn't environment-aware yet (#79), so some of this env is wrong:

```
$ ps aux | grep node | grep -v grep
root     12517  0.0  0.1  36684  1588 ?        Ss   15:10   0:00 sudo -u zoomhub env NODE_ENV=production PORT=3000 BASE_URL=http://zoomhub.net DATA_DIR=/var/data/zoomhub HOME=/home/zoomhub CONTENT_DZIS_PREFIX=dzis/ EXPRESS_LOGGER_FORMAT=default NEW_RELIC_APP_NAME=zoomhub-production NEW_RELIC_LICENSE_KEY=<omitted> NEW_RELIC_NO_CONFIG_FILE=true NEW_RELIC_LOG=/home/zoomhub/newrelic.log RACKSPACE_API_KEY=<omitted> /var/apps/zoomhub/node_modules/.bin/_coffee --cache /var/apps/zoomhub/app
```

Notice the wrong `BASE_URL` and `CONTENT_DZIS_PREFIX`.

But neither of those should be causing this...

**Comment by gasi** [comment]
Closing out old issues. Feel free to reopen if relevant.
