### ISSUE TITLE
Make configuring block storage volume programmatic

### ISSUE THREAD

**Issue by kenperkins** [zoomhub/zoomhub#104]
Currently, we've moved our content to a block storage volume that was hand configured.

We should set this up to be configured through ansible.

**Comment by kenperkins** [comment]
http://docs.ansible.com/rax_cbs_module.html
http://docs.ansible.com/rax_cbs_attachments_module.html

**Comment by gasi** [comment]
Closing out old issues. Feel free to reopen if relevant.
