### ISSUE TITLE
Upgrade production to 2 or 4gb virtual machine

### ISSUE THREAD

**Issue by kenperkins** [zoomhub/zoomhub#106]
Currently we're setup on a 1gb server. We've seen numerous problems with this. Here's my plan for migration
- [x] create a 4gb server
- Configure Server
  - [x] `./zh bootstrap`
  - [ ] `./zh setup`
  - [ ] `./zh deploy`
- [ ] unmount our block storage volume
- [ ] detach the volume
- [ ] snapshot the volume
- [ ] attach to new server
- [ ] mount on new server
- [ ] `./zh deploy`
- [ ] decommission old prod server

**Comment by iangilman** [comment]
Sounds lovely! What do you think, @aseemk? 

@kenperkins Do you need any info from Aseem before rolling this out?

**Comment by kenperkins** [comment]
@iangilman I don't believe so, but I wanted to capture it here so others saw this work item.

**Comment by kenperkins** [comment]
It appears I can't run `./zh setup` on master as the node package is not found. @aseemk I seem to recall you mentioning this?

**Comment by aseemk** [comment]
I fixed it AFAIK for what I encountered: <https://github.com/zoomhub/zoomhub/commit/f49f66b8c0b70a9374d10edce0d430d0a8cae9f5>

For debugging, I found that `apt-cache showpkg nodejs` helped. Via a comment on this answer: http://stackoverflow.com/a/16902348/132978

**Comment by aseemk** [comment]
Btw @iangilman @kenperkins: the general issue SGTM!

**Comment by kenperkins** [comment]
@aseemk I'm not sure it's worth spending time on changes to the version that are going to consistently break; I'm thinking we should proceed on #105

**Comment by gasi** [comment]
Completed with move to Haskell/Keter.
