### ISSUE TITLE
Please add:

### ISSUE THREAD

**Issue by sagupast** [zoomhub/zoomhub#107]
http://zoom.it/gGwh
http://zoom.it/Hewf 
http://zoom.it/H0Tg
http://zoom.it/CGCi
http://zoom.it/hdR9
http://zoom.it/nGe6
http://zoom.it/VCbI
http://zoom.it/GrhI

THANK YOU!!!!

**Comment by iangilman** [comment]
Thanks for the report, and for adding it to #89. Closing this as a duplicate of that.
