### ISSUE TITLE
Queued... still...

### ISSUE THREAD

**Issue by sagupast** [zoomhub/zoomhub#109]
Had a list 12 days ago posted... still not available... ;-(

http://zoom.it/qr6d#full
http://zoom.it/yrZq#full
http://zoom.it/lxww#full
http://zoom.it/DHd#full
http://zoom.it/Qcv7#full
http://zoom.it/az2P#full
http://zoom.it/WtEy#full
http://zoom.it/NgiE#full
http://zoom.it/ku55#full
http://zoom.it/CMTh#full
http://zoom.it/At7E#full

Thanks,
Stephan

**Comment by iangilman** [comment]
Closing as a duplicate of #108. For more information for why it's taking so long, see #89. Also, for alternatives, see #89.
