### ISSUE TITLE
Exporting original image.

### ISSUE THREAD

**Issue by luckcolors** [zoomhub/zoomhub#112]
Hello.
How can i export the original image from zoomhub? Is it possible to implement?
Thanks in advance.

**Comment by iangilman** [comment]
Zoomhub works best if you keep the original image up...think of it as a caching service. If you want the original image, you should grab it from its original location rather than trying to reconstruct it off of Zoomhub.

**Comment by luckcolors** [comment]
The problem is that i don't have the original source.

So is it possible to get the url of the single pieces by doing an api query? So i can wget them?

**Comment by iangilman** [comment]
Sure. Are you familiar with the Deep Zoom Image format? If the image link is http://zoom.it/gSDF, then the API link will be http://api.zoom.it/v1/content/gSDF. From there you can get the link to the DZI file, which in this case would be http://content.zoomhub.net/dzis/gSDF.dzi. The tiles then are at http://content.zoomhub.net/dzis/gSDF_files, in the standard DZI structure.

**Comment by luckcolors** [comment]
OK thanks! :)
Also you probaly forgot that there's the url to the original image in the json metadata.
```
{"id":"gSDF","url":"http://media.stenaline.com/media_SE/givskud-zoo-map/map-bg-no-anim.jpg","ready":true,"failed":false,"progress":1,"shareUrl":"http://zoomhub.net/gSDF","embedHtml":"<script src='http://zoomhub.net/gSDF.js?width=auto&height=400px'></script>","dzi":{"url":"http://content.zoomhub.net/dzis/gSDF.dzi","width":2346,"height":2235,"tileSize":254,"tileOverlap":1,"tileFormat":"jpg"}}
```

**Comment by luckcolors** [comment]
@iangilman I needed to download someone else image. :P
