### ISSUE TITLE
Queud images

### ISSUE THREAD

**Issue by Budsy** [zoomhub/zoomhub#113]
Is there a way to recover the original file? If not...
Any possibility these URLs can be processed and un-queued?? 

http://zoom.it/hF1g
http://zoom.it/ogOy
http://zoom.it/SoMP
http://zoom.it/eCXW
http://zoom.it/9k01
http://zoom.it/Ya4rK
http://zoom.it/JYoy
http://zoom.it/eCXW
http://zoom.it/nDwU
http://zoom.it/b2eR
http://zoom.it/JAVx 
http://zoom.it/OUoO
http://zoom.it/GAHlC
http://zoom.it/DD3H
http://zoom.it/z8lO
http://zoom.it/n65V
http://zoom.it/HIqm

**Comment by iangilman** [comment]
You can find the original URL through the API. Here is the call for the top one on your list: 

http://api.zoom.it/v1/content/hF1g

You can see in the result: 

```
{"id":"hF1g","url":"http://cosmo2.net/focmaps/Weitas_Creek.jpg","ready":false,"failed":false,"progress":0,"shareUrl":"http://zoomhub.net/hF1g","embedHtml":"<script src='http://zoomhub.net/hF1g.js?width=auto&height=400px'></script>"}
```

...that the original URL for that image is: 

http://cosmo2.net/focmaps/Weitas_Creek.jpg

Unfortunately that URL is now giving a 404. Zoom.it relies on that original URL, so it won't be able to process any images that are missing like that (even when the service is up and running again).

**Comment by Budsy** [comment]
Thanks very much Ian, 

 

I figured out that because the source URLs and files no longer exists that was the problem of the 404.  I have a workaround now working, my client is happy, so all is well. 

 

Best, Bob Dickow (Budsy)

Buffalo Girls Productions

**Comment by iangilman** [comment]
@Budsy Good to hear!
