### ISSUE TITLE
Improved homepage

### ISSUE THREAD

**Issue by iangilman** [zoomhub/zoomhub#114]
@gasi suggests:

> how about some frontend work with a prettier and more importantly, a more explanatory homepage that shows the beauty of zooming :heart:?

**Comment by gasi** [comment]
FWIW, the old homepage looked like this:

![pasted_image_12_1_15__10_53_pm](https://cloud.githubusercontent.com/assets/49583/11524277/60bbbb8e-987e-11e5-8d4e-ff2a4a55d958.png)

I don’t find it particularly informative for a newcomer but pretty it was :eyes: :smile:

**Comment by gasi** [comment]
Done.
