### ISSUE TITLE
Queued... please help

### ISSUE THREAD

**Issue by nataluchi** [zoomhub/zoomhub#121]
Hello, i've been using a zoomhub page lately for some research, but a few days ago, the page began to appear as "ZoomHub - Queued..." i don't know how to fix it, it is actually an old file from ZoomIt so when i started looking for a solution i read that all the files from Zoomit are fixed now; but apparently not. Can you help me **please**? I've tried myself to get it back but now i feel desperate. :(

This is the url: http://zoom.it/Mbqhq#full

**Comment by gasi** [comment]
@nataluchi Thanks for your report. ZoomHub (formerly Zoom.it) is a caching service, so it relies on the original source to be present. In your case, unfortunately, the source content at https://dl.dropboxusercontent.com/u/12646788/zoom.tif is gone and returns a `404 Not Found`. Would it be possible for you to put the content back? When you do, let me know and I’ll reconvert it 😄 

Metadata: http://zoomhub.net/v1/content/Mbqhq

I apologize for the troubles.

**Comment by nataluchi** [comment]
Dear Gasi, thank you so much for replying so fast. It seems that the site is fixed now, you were very helpful and i appreciate it!!! :) :+1:

**Comment by gasi** [comment]
@nataluchi I found your content in a previous backup and restored it to the best of my ability. I am glad it worked out 😄 May I ask, what do you use ZoomHub for? I am trying to learn and build features that people like.

**Comment by nataluchi** [comment]
Thank you Gasi!!! i use ZoomHub for architecture presentations mostly. :) :+1:

**Comment by gasi** [comment]
@nataluchi Sweet, thanks for explaining! Do you have a page/presentation you could share? I’d like to learn more 😄

**Comment by iangilman** [comment]
@nataluchi Also, we'd love to be able to promote your work, if it's public! See https://github.com/zoomhub/zoomhub/issues/122
