### ISSUE TITLE
Missing images: digitalmonalisa.com

### ISSUE THREAD

**Issue by andypatros** [zoomhub/zoomhub#123]
Hi,

I’m an existing user of Zoom It on my website at http://www.digitalmonalisa.com/zoom1.html

It is not working and wondered why.

Thanks,
Andy Patros

**Comment by gasi** [comment]
@andypatros: I checked your website but can’t find any reference to Zoom.it / ZoomHub.net. Can you tell me which image on Zoom.it is queued for you?

**Comment by andypatros** [comment]
Daniel,

I removed the zoomhub link and started using sirv.com's similar service, when I saw the zoomhub problem a few days ago.

I first used zoom.it when it was a Microsoft service, so that had to be 3-4 years ago.

Can it be fixed if I get you the image file name?

Andy Patros

Louis is right!
http://youtu.be/E2VCwBzGdPM

**Comment by gasi** [comment]
@andypatros Yes, we may be able to restore your images if you give us all the URLs. We have been reprocessing old files in the background during the past 8 months.

**Comment by gasi** [comment]
@andypatros I’ll close this issue to keep the backlog tidy but please comment here if you’d like to reinstate your images on @zoomhub.
