### ISSUE TITLE
Posters on SharePoint 2013 page is queued

### ISSUE THREAD

**Issue by ricachet** [zoomhub/zoomhub#125]
the posters listed at the bottom of the page are stuck on queued
https://technet.microsoft.com/en-us/office/dn788776

**Comment by gasi** [comment]
@ricachet Thanks for reporting these, but when I checked their sources, they were gone, meaning I can’t restore them. Example: http://technet.microsoft.com/ff678313.temporary-zoom-it-image-105.gif

If you know how to get the original file, I could try restoring them.
