### ISSUE TITLE
http://zoom.it/hHWw

### ISSUE THREAD

**Issue by c2757371** [zoomhub/zoomhub#127]
http://zoom.it/hHWw is not working? Who can help?

**Comment by gasi** [comment]
@c2757371: Thanks for reporting this. I tried requeuing it but the underlying source image (URL) is not available: https://dl.dropboxusercontent.com/s/hahixgb3hhjr56n/isaiahs_principle_by_louise_bostanian_low_dpi.png?dl=1

Could you restore it?

See: http://zoom.it/v1/content/hHWw

**Comment by c2757371** [comment]
@gasi Thanks! Unfortunately, I can't restore it.

**Comment by gasi** [comment]
@c2757371 Sorry to hear. I redacted the links. Let me know if you get the file back.

**Comment by c2757371** [comment]
@gasi I got it: http://bit.ly/1WQJFNE Does that work?

**Comment by gasi** [comment]
@c2757371 I tried that URL and I can see a download page when I am logged into Dropbox, but it doesn’t work for Zoom.it. Can you share it at a publicly accessible URL? Thanks 😄
