### ISSUE TITLE
I can not access a file: OVzp

### ISSUE THREAD

**Issue by dyeya** [zoomhub/zoomhub#129]
this file     http://zoom.it/OVzp#full   can not be opened

**Comment by gasi** [comment]
@dyeya Thanks for your request. Unfortunately, the underlying file is gone and I won’t be able to restore your image: https://dl.dropboxusercontent.com/u/3527548/Artemisa_Espinosa.tif

See: http://zoom.it/v1/content/OVzp

Can you restore that file?

**Comment by gasi** [comment]
@dyeya I haven’t heard back from you, so I will close this issue. Please feel free to comment on #89 once you have restored the underlying file.
