### ISSUE TITLE
restoring old image

### ISSUE THREAD

**Issue by paulgt11** [zoomhub/zoomhub#130]
Hi guys, 
back in 2014, i asked if you would be able to recover an old image.
The original reference was zoom.it/5eha. 
It is a large .tif image of a local cemetery that helps families and family historians locate their ancestors in our local cemetery.
it was originally logged on issues/89, but that was back then and that issue is now closed, hence adding a message here. 

I do hope that you are still able to recover this image.

With Thanks
Paul Thompson

**Comment by gasi** [comment]
Thanks for reaching out @paulgt11. Your image is back online: http://zoom.it/5eha Enjoy 😄

**Comment by paulgt11** [comment]
Thanks Everyone.

**Comment by paulgt11** [comment]
hi Guys, 
is it possible to revisit this image?
I have noticed that the bottom quarter is missing. This is a very large file and your systems may not be able to handle it as it 319Mb. 
I have added a good copy of the file to my drop box account where the images are stored. (Link below)
if you are able to regenerate from the .tif file, i would be most grateful. if all else fails, try with the .jpg.
Thanks very much.

https://www.dropbox.com/sh/liccurri6o1a8ou/AAB5Wfmmie26yNJeOSaxtrGUa?dl=0

**Comment by gasi** [comment]
@paulgt11 Thanks for pointing out the issue. I tried downloading the TIFF file twice in Chrome and once in Safari and it always ends up being 242.8MB. Opening that file in _Preview_ and _Photoshop_ results in a warning that the file is corrupted and the bottom part is missing. Can you check the source again?

Unfortunately, ZoomHub currently doesn’t work with Dropbox links.

**Comment by paulgt11** [comment]
HI @gasi . My apologies for the problem with the tiff file. I was not aware that it was corrupt on the website. I have now replaced it with a good version and you should be able to download it.

**Comment by gasi** [comment]
@paulgt11 Thanks. Looks like we got it all this time. Mind confirming? http://zoom.it/5eha

**Comment by paulgt11** [comment]
Thanks @gasi . The image is perfect this time.

**Comment by paulgt11** [comment]
Hi @gasi,
When i viewed the image from my mobile this morning it looked intact; however from a desktop computer or from the website, there are segments missing in the initial view.
As you zoom in, they disappear and some other gaps appear in the early stages, but every thing is okay on the close-ups.
It is like there are some segments that have not transferred leaving holes in the map.

I would be grateful if you could check it once more. 

Thanks very much 
Paul T

**Comment by gasi** [comment]
@paulgt11 I noticed these gaps too, the first time the corrupted image was converted. Now when I try in a clean browser / browser with history deleted, I don’t see those black holes. Mind clearing your browser history & cache and try again?

**Comment by paulgt11** [comment]
Hi @gasi 
Thanks for the update. It works fine with the browser. I won't trouble you again. :)
Your time and effort is most appreciated.

Best wishes
Paul T

**Comment by gasi** [comment]
@paulgt11 You are no trouble at all — I want to make sure your needs are met and your image is displayed correctly 😄 Please let me know if you encountered any further issues — I’d be happy to help where I can.
