### ISSUE TITLE
license

### ISSUE THREAD

**Issue by eltonnobrega** [zoomhub/zoomhub#132]
Good Morning. Is it allowed to use deep zoom format on my imaging site? I have seen that this format has a proprietary license.

**Comment by gasi** [comment]
@eltonnobrega What are you referring to specifically? The Deep Zoom Image (DZI) format, the OpenSeadragon library, or zoom.it/ZoomHub? Each has their own licensing terms. Let me know and I'll try to help. I am confident we'll find something that works for you.

**Comment by gasi** [comment]
@eltonnobrega I am not aware of the Deep Zoom format (DZI) itself having any licensing restrictions and many people use it on their sites:

- Artsy: https://www.artsy.net/artwork/saint-clair-cemin-greece/zoom
- Chris Jordan: http://chrisjordan.com/gallery/rtn/
- NYT: https://www.nytimes.com/interactive/2017/01/20/us/politics/trump-inauguration-photo-zoomer.html?_r=0

More: https://openseadragon.github.io/examples/in-the-wild/

I will close this issue but feel free to reopen if you have more questions.
