### ISSUE TITLE
[Frontend][Perf] Potential huge optimization

### ISSUE THREAD

**Issue by pavelloz** [zoomhub/zoomhub#185]
I have noticed that the 178KB script is loaded couple of times on homepage ( https://www.zoomhub.net/ )
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/546845/136403917-df244b96-aa99-4674-8dca-7f1090ead28a.png">

Ive run diff on them from curiosity and it looks like the difference is less than 1KB.
Because all files have different file names, they are not cached and are parsed, executed couple of times. This probably hurt performance a lot. [1]

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/546845/136404100-f4556e56-e717-48e3-b596-8cd691001cb1.png">

I would recommend loading the vendor script once, and extracting this 1 KB difference into their own javascripts and then loading only the difference. Or even inlining the difference - its small enough to benefit from http requests reduction.
  
Additionally, enabling gzip compression would make it much more bearable - if you use S3/CF for serving assets it should be pretty easy to do.

[1] https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwww.zoomhub.net%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo

**Comment by gasi** [comment]
@pavelloz Thanks for the detailed write-up. I’ve had a chance to play around with Tailwind CSS and I find it promising. Thanks for the offer to create a sample configuration, but I was able to get up and running on my own. It’s still early, but feel free to take a look here: https://github.com/zoomhub/zoomhub/pull/186

**Comment by gasi** [comment]
The homepage has been redesigned with a single image and Tailwind, so I’ll close this.

**Comment by iangilman** [comment]
Nice! 🎉
