### ISSUE TITLE
JPEG 2000 support

### ISSUE THREAD

**Issue by acdha** [zoomhub/zoomhub#25]
I've heard some comments recently that it'd be useful to have a simple standalone service which could serve JPEG tiles from a directory of JPEG-2000 masters without requiring a complicated media management pipeline. The use-case being things like technicians being able to review batches of new scans, efficient internal access to large files which aren't yet on a public website, etc. This made me think of Zoomhub and I was wondering what you thought of the idea. 

Based on a cursory look at the code it seems like this would entail something like finding / writing [OpenJPEG](http://www.openjpeg.org) bindings for https://github.com/openzoom/node-deepzoomtools and making sure the API allows the tiled decoding optimization.

**Comment by gasi** [comment]
Closing this as it’s been open for over 18 months. @acdha Feel free to reopen if there is still interest in submitting this :+1:
