### ISSUE TITLE
Controls don't work on iPhone

### ISSUE THREAD

**Issue by iangilman** [zoomhub/zoomhub#27]
From @supercc: "I noticed the buttons + and - and home and the other one does not work when you open a image in the iPhone 5. Also the double tap to zoom in does not work. When I zoom in with the 2 fingers gesture, I can see little black squares blicking here and there while zooming on the pictures, still on the IPhone. I did not see this issue on the windows explorer."

I think the fix is just to upgrade OpenSeadragon; much better touch support in the recent version.

**Comment by gasi** [comment]
@iangilman Is the upgrade to the latest OpenSeadragon something you could/would want to help out with? No pressure :heart:
