### ISSUE TITLE
Improve instructions for setting up on your own server

### ISSUE THREAD

**Issue by iangilman** [zoomhub/zoomhub#28]
We have:

https://github.com/zoomhub/zoomhub/blob/master/README.md
https://github.com/zoomhub/zoomhub/blob/master/CONTRIBUTING.md

… but we can probably improve upon that.

Pile on this thread with suggestions and questions!

**Comment by leandrotlz** [comment]
Once all the dependencies are met and `./zh install` is run, there is no more guidance on how to actually upload images, or even basic server configuration. `./zh run` will start the server on port 8000, but that only displays the same notice that you can see in zoom.it. `./zh setup` asks for a vault password that is not listed anywhere, so at this point I'm stuck.

**Comment by iangilman** [comment]
Unfortunately at this point, it's not really ready to be deployed elsewhere. I don't know the details, but I imagine the vault password has to do with the file store we're using on Rackspace. Ideally we'd have that module pluggable so you could use a file store on another provider if you wanted to. 

In addition, being able to upload new images is not yet working (see #60, #63, and #89). 

Development on these issues has stalled, due to time constraints on the original developers. I'd love to get some movement on them, though. Would you be up for helping out with the development?

**Comment by gasi** [comment]
Yes, I can confirm that so far this has only been tested for us to deploy to our own Rackspace account. It hasn’t been tested for setup on a different account yet, but it could work if you want to try it on your own Rackspace account by following these steps: https://github.com/zoomhub/zoomhub#administation

**Comment by gasi** [comment]
Closing this as our current priority is probably less focused on self-hosting. However, feel free to contribute to our server setup and/or documentation :eyes: :heart:
