### ISSUE TITLE
investigate broken images

### ISSUE THREAD

**Issue by iangilman** [zoomhub/zoomhub#29]
@supercc recently tried to convert a number of images, and while some of them worked, many did not. We should figure out why. These are the IDs for the broken images: `8`, `9`, `10`, `11`, `12`, `15`.

Also a great future feature would be some sort of logging/reporting so we automatically became aware of broken images.

**Comment by gasi** [comment]
Converted where possible:

- http://zoom.it/8
- http://zoom.it/9 (404)
- http://zoom.it/10 (404)
- http://zoom.it/11 (404)
- http://zoom.it/12 (non-existent ID)
- http://zoom.it/15

PEDO BEAR IS BACK!!

![](http://img.myconfinedspace.com/wp-content/uploads/2008/03/pedo-bear-seal-of-approval.png)

**Comment by iangilman** [comment]
There's a blast from the past!
