### ISSUE TITLE
ops: Add log rotation

### ISSUE THREAD

**Issue by gasi** [zoomhub/zoomhub#34]
Our current log file has grown to 56MB. I don’t believe it caused any issue so far but we should be smarter about log file growth down the line.

Edit by @aseemk: related issue #77 for aggregating.

**Comment by aseemk** [comment]
Re-opening, as we haven't made any progress on aggregation/forwarding (#77), and our current log has grown to 7.6 GB! :open_mouth: 

```
$ du -sh /var/log/zoomhub/*
7.6G	zoomhub.log
5.7M	zoomhub.snapshot01.log
44M		zoomhub.snapshot02.log
```

Yikes. I remember taking those snapshots manually before, but that was via `cp ... && rm ...` (just `mv` doesn't do the trick), and we no longer have enough space for that now:

```
$ cp zoomhub.log zoomhub.snapshot03.log && cat /dev/null > zoomhub.log
cp: writing `zoomhub.snapshot03.log': No space left on device
cp: failed to extend `zoomhub.snapshot03.log': No space left on device
```

It looks like about 5 GB gets copied before that message, which means we have only a couple more months left before our server runs out of disk space. :open_mouth: 

/cc @kenperkins: are you comfortable snapshotting/rotating logs? If so, we can do so on a cron job, and archive the snapshots to CloudFiles to keep disk space constant.

**Comment by gasi** [comment]
We have log rotation with Haskell/Keter now and (so far) plenty of disk space:

```
admin@zoomhub:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       79G   29G   47G  39% /
```

**Comment by gasi** [comment]
Closing out old issues. Feel free to reopen if relevant.
