### ISSUE TITLE
Ops: way to use env during manual SSH

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#48]
Scenario: I've SSH'ed in and want to run a script we have checked into our repo, which uses our config. Since I'm on a production machine, I want to use production configs. (E.g. `DATA_DIR`.)

(Analogy: `heroku run bash`.)

Problem: the env is only set for the main web server run command.

https://github.com/zoomhub/zoomhub/blob/b23d8a025513913360a64f57080ffbb479bc0c1e/deployment/roles/web/templates/service.conf.j2#L14

And the env is defined only in Ansible here:

https://github.com/zoomhub/zoomhub/blob/b23d8a025513913360a64f57080ffbb479bc0c1e/deployment/group_vars/webservers.yml#L12-L19

Ideas for solutions:
- Have Ansible set the env globally? E.g. as part of server setup.
- Have an Ansible command to SSH into the server and set the env as the first action.

Not sure what the pros/cons are, or if there are other approaches.

/cc @gasi

**Comment by gasi** [comment]
:+1: for `bash_profile`. Who’s got the Ansible magic :sparkles:? :smile:

**Comment by gasi** [comment]
Closing out old issues. Feel free to reopen if relevant.
