### ISSUE TITLE
Ops: compile code before running

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#49]
Instead of compiling on the fly. Even though we cache, if a significant amount of code has changed, server startup is delayed.

We should still place the compiled output separately from the git source, though, so that cruft doesn't accumulate (or worse, cause bugs) as we rename and remove files, etc.

Analogy: Heroku has a notion of an explicit "build" directory where it runs build steps on, and then only copies/rsyncs the result to the "run"/app directory afterward.

**Comment by gasi** [comment]
Done in v2 (by necessity) :wink:
