### ISSUE TITLE
Ops: zero-downtime deploys

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#50]
Right now, we explicitly restart our Node server, which means users see downtime for the span of the restart. Not a huge deal for now, but we should figure this out at some point.

Heroku achieves this by having a separate routing layer from the app layer, and the router holds onto open requests while the app is starting up.

I don't know how to achieve this on a single server, though I'm sure there's literature on this.

**Comment by gasi** [comment]
We have this now with Haskell/Keter. Closing for now. Feel free to reopen if relevant.
