### ISSUE TITLE
Zoom.it transfer

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#57]
Working on setting up the pre-reqs for this now; just tracking.

- [x] Replicate DNS records (AKA zonefile) on our nameservers (still pointing to Microsoft servers)
- [x] David points domain (still owned by Microsoft) to our nameservers
- [x] David transfers domain to us (pointing to our nameservers, which still point to Microsoft servers)
- [x] We update the DNS records on our nameservers to point to our Rackspace servers

Ideally most of this we do beginning of next week, but at least the first step I can do beforehand.

**Comment by gasi** [comment]
Seems resolved, right? Feel free to reopen.
