### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by kenperkins** [zoomhub/zoomhub#64]
Looking through our `total.txt` list of top images, I noticed that ~212 were missing from our content-by-id directory, and a dozen more or so had empty JSON. One had no `dzi` property: `./data/_Yev6.json`.

Do we have any idea why these would be a problem for our local db?

**Comment by gasi** [comment]
In the process of importing `missing-data.zip` on the v2 server.

**Comment by gasi** [comment]
Closing out old issues. Feel free to reopen if relevant.
