### ISSUE TITLE
Logo!

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#71]
We should get a proper logo. =)

Places to use it:
- [ ] Twitter avatar
- [ ] GitHub avatar
- [ ] Website favicon
- [ ] Website UI

**Comment by gasi** [comment]
Added new logo. Closing for now. Feel free to reopen if relevant.

**Comment by gasi** [comment]
<img width="1239" alt="zoomhub___zoomhub____twitter" src="https://cloud.githubusercontent.com/assets/49583/21437386/6476675c-c838-11e6-8b39-19485da403b5.png">

**Comment by iangilman** [comment]
Looking good! Great to see the action here and on Twitter :-)
