### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#72]
Not urgent at (zoom.it never had it), but at some point, we should support HTTPS.

https://zoomhub.net/

We don't _need_ it, but in this day and age, it's easy to expect it. E.g. turns out our own Twitter profile actually assumed it (fixed).

**Comment by mef** [comment]
> We don't need it

Absence of https support prevents to use the zoom.it embed script inside https pages, in the more recent version of browsers. So it seems this issue is more problematic now.

**Comment by gasi** [comment]
@mef Thanks for the feedback. None of us are currently actively working on Zoom.it. Do you happen to know an easy way to set up HTTPS on an Ubuntu / Haskell stack? I’d appreciate your help.

**Comment by gasi** [comment]
@mef First of all, thanks for your patience. This is live now. Please give it a spin and let me know if you find anything amiss 🙇‍♂️

**Comment by mef** [comment]
Thanks @gasi, great to see this one fixed, it works perfectly :)
