### ISSUE TITLE
Forward logs into Splunk

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#77]
E.g. into Splunk. (I set up a free SplunkStorm account; creds in passwords.md.)

https://www.splunkstorm.com/storm/deployment/data/overview/b576089a54ab11e4b52e22000ab5bb50

Documentation on forwarding our logs:

http://docs.splunk.com/Documentation/Storm/latest/User/Setupauniversalforwarderonnix

@gasi knows this stuff well.

Edit: related issue #34 for rotating.

**Comment by aseemk** [comment]
Just an update that Splunk closed our account a while back due to inactivity.

**Comment by gasi** [comment]
Splunk discontinued their free hosted Splunk offering. There is now _Splunk Light_ for 500MB/day for free. I tested it locally and it works fine. I’ll see if I can set it up on an admin machine.

**Comment by gasi** [comment]
We have Splunk logs now. Closing issue for now. Feel free to reopen if relevant.

**Comment by gasi** [comment]
See: http://admin.zoomhub.net:8000/
