### ISSUE TITLE
Simple queue and throttling of work

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#8]
_Edit: ignore much of the below. See first comment for update._

We'll eventually want our workers (#7) to run separately from our web servers. To achieve that, we'll need a queueing system.

Tasks:
- [ ] Add a queue interface, just like the interfaces to tile storage (#2) and to the database (#3).
- [ ] Implement a basic implementation of the queue interface. The simplest way here too would be to just a local file (e.g. JSON) on disk.
- [ ] Update the web server to enqueue new work.
- [ ] Update the worker to poll the queue.

We don't _need_ this for a rough initial prototype, though: the web server can just kick off an async process when it gets an API request to convert a new image. This is in fact what our very first Zoom.it prototype did. ;)

**Comment by aseemk** [comment]
Okay, so shipped pull #94 tonight which added a worker and lazy on-demand processing of old content... and things became a shit-show.

In retrospect, makes sense: we get a couple hundred requests per minute, so all those views were triggering work. That caused an exhaustion of inode capacity on the server.

(And substantial work wasn't even getting done: VIPS wasn't getting picked up. #101)

This suggests that before we turn something like that back on, we should have a proper queue now, and throttling of workers.

Related issue #63 for moving to a proper db, and as noted in a comment there, we could probably take advantage of us having only one web server for now, and just have the queue in-memory.

Then, we could run one or more workers in the background polling this in-memory queue.

**Comment by iangilman** [comment]
We get a couple hundred requests for "queued" content per minute? Wow… That's a lot!

In that case there might be something to be said for explicitly doing all of the items mentioned in #89 first, and then turning on the "on-demand" thing (once we can throttle it). I agree an in-memory queue would be the most expedient, and then we can move to a database once we've got one.

**Comment by aseemk** [comment]
I took a deeper look at our instrumentation on New Relic:

https://rpm.newrelic.com/accounts/790628/applications/4061651/transactions#sort_by=throughput

And I'm off by about an order of magnitude: most of the requests are actually to our `queued.dzi` *tiles*. We should move those to our CDN'ed Cloud Files; I'll create an issue for that.

So over the past 24 hours, our average throughput for content (across embeds, API reqs, and pageviews) has been ~35 rpm. Still more than significant from a worker perspective.

I agree that given that, we should just manually process the most important content for now. Unfortunately, two things are still an issue w/ that:

- VIPS isn't getting picked up on the server, which is a blocking issue. (#101)

- We're still basically out of inodes / file handles, and given that DZI works with many small files, my hypothesis is that even generating content one-by-one manually is still going to cause issues, until we move our 1M+ db files to Cloud Files. (#63)

**Comment by gasi** [comment]
We are now queuing via our PostgreSQL database.
