### ISSUE TITLE
Continuous deployment from Travis

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#86]
We now have decent test coverage and automated CI through Travis, so let's get CD going too.

I assume the best way would be to have/let Travis deploy after a successful CI, but that _does_ require us to give our production keys to a third-party service, which isn't great. I'm okay w/ it though, as there isn't any better _but still simple_ alternative.

(At FiftyThree, we run a separate service which does the actual deploying; Travis hits that `after_success`. But maintaining a separate service would be way overkill for us right now.)

Speaking of `after_success`, our deploy is via an Ansible playbook, which Travis doesn't have any built-in integration for, so I think we have to achieve it manually via `after_success` too:

http://docs.travis-ci.com/user/deployment/
http://docs.travis-ci.com/user/deployment/custom/

So I believe we have to use Travis's encrypted variable support to encrypt a private SSH key as well as the Ansible Vault password, so that it can do the actual deploying.

http://docs.travis-ci.com/user/encryption-keys/
http://docs.travis-ci.com/user/encrypting-files/

WDYT @kenperkins @gasi?

**Comment by gasi** [comment]
Completed this with move to Haskell/Keter. Closing issue for now. Feel free to reopen if relevant.
