### ISSUE TITLE
All zoom.it images are gone!

### ISSUE THREAD

**Issue by narend** [zoomhub/zoomhub#91]
I had many zoom.it images and all seem to be gone. I at least need a way to back up in my store. Any way I can retrieve them, please

**Comment by narend** [comment]
Thanks for the reply. Here are the images we are using in the public site http://digitalnarratives.net . These are now broken, and I could not trace original images. It'd be great if these are ported over. Thanks in advance!

http://zoom.it/dPNH
http://zoom.it/U29d
http://zoom.it/HYDt
http://zoom.it/QhBF
http://zoom.it/yCKg
http://zoom.it/JXTl
http://zoom.it/cOEr
http://zoom.it/uLib
http://zoom.it/goNi
http://zoom.it/kR5s
http://zoom.it/3nEC
http://zoom.it/L36z
http://zoom.it/PV9c
http://zoom.it/qCW1
http://zoom.it/MRqd
http://zoom.it/Jl6r
http://zoom.it/LVyO
http://zoom.it/Syfo
http://zoom.it/BgcI
http://zoom.it/V2vx
http://zoom.it/1DPj
http://zoom.it/2Mbc
http://zoom.it/k5aG
http://zoom.it/tUYc
http://zoom.it/GmNB
http://zoom.it/LZr5
http://zoom.it/Jpwr
http://zoom.it/51yd
http://zoom.it/hdfm
http://zoom.it/McjX
http://zoom.it/4IOE
http://zoom.it/Xl7o
http://zoom.it/9TYR
http://zoom.it/gvPD
http://zoom.it/QdQl
http://zoom.it/y8Ow
http://zoom.it/D4A0
http://zoom.it/6zhS
http://zoom.it/EB8Y
http://zoom.it/dXUf
http://zoom.it/1z8J
http://zoom.it/T9XM
http://zoom.it/ERo1
http://zoom.it/oBvR
http://zoom.it/qRko
http://zoom.it/Rs1I
http://zoom.it/CiJc
http://zoom.it/zMNg
http://zoom.it/Go1K
http://zoom.it/YIcl
http://zoom.it/VYk3
http://zoom.it/d9Q7
http://zoom.it/VQ74
http://zoom.it/Hixh
http://zoom.it/8Q3
http://zoom.it/76UN
http://zoom.it/6h65
http://zoom.it/P5Ti
http://zoom.it/jQ55
http://zoom.it/8XML
http://zoom.it/4dWT
http://zoom.it/bFbQ
http://zoom.it/nNwK
http://zoom.it/2KZA
http://zoom.it/S9eW
http://zoom.it/nJsP
http://zoom.it/41G7
http://zoom.it/3LZS
http://zoom.it/kmKa
http://zoom.it/k9C9
http://zoom.it/kdXa
http://zoom.it/BsyK
http://zoom.it/U3qd
http://zoom.it/yAHz
http://zoom.it/QuHk
http://zoom.it/K6O6
http://zoom.it/gEqO
http://zoom.it/4hkg
http://zoom.it/BAyA
http://zoom.it/6jV1
http://zoom.it/NPge
http://zoom.it/9mBP
http://zoom.it/V1M6
http://zoom.it/pH6f
http://zoom.it/Fbjz
http://zoom.it/Nzzo
http://zoom.it/JbO0
http://zoom.it/3E7e
http://zoom.it/IOeS
http://zoom.it/oQTF
http://zoom.it/YRM1
http://zoom.it/gj4c
http://zoom.it/dtdr
http://zoom.it/KFRR
http://zoom.it/W780
http://zoom.it/8LDZ
http://zoom.it/t56y
http://zoom.it/CCCu
http://zoom.it/dcYU
http://zoom.it/uAyU
http://zoom.it/rgjj
http://zoom.it/c84G
http://zoom.it/calr
http://zoom.it/aS5A
http://zoom.it/M1yi
http://zoom.it/oXkZ
http://zoom.it/2GQO
http://zoom.it/coDC
http://zoom.it/8qLY
http://zoom.it/UKOB
http://zoom.it/XHcw
http://zoom.it/g8T3
http://zoom.it/4uLI
http://zoom.it/GEFC
http://zoom.it/BLzx
http://zoom.it/MuuOZ
http://zoom.it/PHNm
http://zoom.it/76qy
http://zoom.it/uyb7
http://zoom.it/ga1Y
http://zoom.it/fD0L
http://zoom.it/rCi5
http://zoom.it/RITE
http://zoom.it/vTom
http://zoom.it/Ycil
http://zoom.it/FREj
http://zoom.it/CQTb
http://zoom.it/Pvjl
http://zoom.it/UDYF
http://zoom.it/J5HF
http://zoom.it/5jJF
http://zoom.it/N6HF
http://zoom.it/VAld
http://zoom.it/60Vz
http://zoom.it/iMfc
http://zoom.it/wbjm
http://zoom.it/rnGU
http://zoom.it/q50W
http://zoom.it/Gan0
http://zoom.it/HzW4
http://cache.zoom.it/content/UTcM.dzi
http://cache.zoom.it/content/EigE.dzi
http://cache.zoom.it/content/5v0a.dzi
http://cache.zoom.it/content/VlO0.dzi
http://cache.zoom.it/content/CMEO.dzi
http://cache.zoom.it/content/tnH8.dzi
http://cache.zoom.it/content/Xska.dzi
http://cache.zoom.it/content/Xygm.dzi
http://cache.zoom.it/content/69BU.dzi
http://cache.zoom.it/content/OO18.dzi
http://cache.zoom.it/content/IEHB.dzi
http://cache.zoom.it/content/8wxw.dzi
http://cache.zoom.it/content/pCoJ.dzi
http://cache.zoom.it/content/21UI.dzi
http://cache.zoom.it/content/MyYX.dzi
http://cache.zoom.it/content/dthU.dzi

**Comment by narend** [comment]
Hi iangilman, Can the above images be please restored? We are relying on them for a public facing site and getting these up would help us so much. Thanks in advance.

**Comment by iangilman** [comment]
Yes, I'm sorry it's taking so long! We are moving forward, if slowly. I'll keep you posted.

**Comment by johntester** [comment]
Hi, we had 2 info graphic images on arupconnect.com, can you please restore these 2 images:
http://zoomhub.net/v1/content/4W3O
http://zoomhub.net/v1/content/WFcM

**Comment by aseemk** [comment]
This isn't *exactly* closed yet — just implemented a bunch of code to do this, but still need to actually run it in production — but hope to do that very soon. =)

**Comment by aseemk** [comment]
Server issues tonight preventing progress here unfortunately. Stay tuned...

**Comment by narend** [comment]
It has been few months and I need these urgently. Any updates please?
Thanks in advance!

**Comment by iangilman** [comment]
@narend Yes, I'm sorry it's taking so long! It's a combination of some thorny technical issues and a team of volunteers with demanding day jobs. I honestly don't know how much longer it will be. 

If you need it urgently, you might consider trying http://zoomable.ca or working directly with http://openseadragon.github.io. If you do the former, @abrlam may be able to provide guidance; for the latter, feel free to ask me for help over in https://github.com/openseadragon/openseadragon/issues. 

Apologies again for the delay!

**Comment by abrlam** [comment]
Thank you for the referral Ian!@narend, would you by any chance still have the originals? If so, I'm more than happy to assist you in having them up online on our site.Abraham                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: Ian GilmanSent: Wednesday, May 6, 2015 12:50 PMTo: zoomhub/zoomhubReply To: zoomhub/zoomhubCc: abrlamSubject: Re: [zoomhub] All zoom.it images are gone! (#91)@narend Yes, I'm sorry it's taking so long! It's a combination of some thorny technical issues and a team of volunteers with demanding day jobs. I honestly don't know how much longer it will be. 

If you need it urgently, you might consider trying http://zoomable.ca or working directly with http://openseadragon.github.io. If you do the former, @abrlam may be able to provide guidance; for the latter, feel free to ask me for help over in https://github.com/openseadragon/openseadragon/issues. 

Apologies again for the delay! 

—Reply to this email directly or view it on GitHub.

**Comment by abrlam** [comment]
Hi @narend, please check the message above for updates (new links provided).  Thank you.

**Comment by gasi** [comment]
@narend I was able to restore most of your images except for these:

```
id="4uLI", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/2-Livestock.JPG
id="GEFC", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/3-Sheep.JPG
id="BLzx", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/4-Livestock.JPG
id="MuuOZ", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/5-Livestock.JPG
id="PHNm", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/6-Herding.JPG
id="76qy", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/8-Woman%20Churning%20Milk.JPG
id="uyb7", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/9-Storing%20Butter%20In%20Goat%20Stomach%20Bag.JPG
id="ga1Y", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/11-Spinning%20and%20Weaving.JPG
id="fD0L", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/12-Weavers.JPG
id="rCi5", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/1-Livestock/13-Livestock%20Uses%20in%20Daily%20Life.JPG
id="RITE", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/2-Ploughing%20With%20Yaks.JPG
id="vTom", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/3-Ploughing%20With%20Yaks.JPG
id="Ycil", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/4-Fertile%20Valley.JPG
id="FREj", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/5-Fertile%20Valley.JPG
id="CQTb", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/6-Fertile%20Valley.JPG
id="Pvjl", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/7-Stepped%20Farms.JPG
id="UDYF", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/8-Stepped%20Farms.JPG
id="J5HF", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/9-Khurambrik%20Farm.JPG
id="5jJF", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/10-Barley%20Weeds.JPG
id="N6HF", error=Error: 404 response from http://wdh.blob.core.windows.net/deepzoom-sources/ladakh/CBAgricultureAndLivelihood/2-Farming%20And%20Crops/11-Barley%20Weeds.JPG
```

Let me know if you restore them and I can give it another shot :smile: 

/cc @iangilman @aseemk

**Comment by gasi** [comment]
@johntester: Sorry, your source images resulted in 404s. Please let me know once they are up again :smile:
