### ISSUE TITLE
Return to URL symlinks in flat-file DB

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#95]
The original design of the flat-file db was intended to be e.g.:

```
content-by-id/
- a.json
- b.json
- ...
content-by-url/
- <hash> —→ ../a.json
- <hash> —→ ../b.json
- ...
```

However, while preparing for our big v1 launch, we scrapped the URL symlinks and instead used a single `data.json` file containing all URL-to-ID mappings as one giant dictionary (commit <https://github.com/zoomhub/zoomhub/commit/01d9bf3e02f7eead653872dc6bcdfe48cd9f0768>).

This was fine for launch, but `require()`'ing that file means that entire mapping is in memory, and today we spiked and almost ran out of memory on our production server.

We know we want to move to a proper database (issue #63), but that's probably still a ways away. In the meantime, can we re-introduce symlinks and get rid of this giant `data.json` file?

**Comment by aseemk** [comment]
Ultimately, we have to traverse the entire dictionary (or the `content-by-id` directory) and create a symlink for each entry (or ID) there.

That's probably not an option, because our production server probably doesn't have the memory to do that, while our user-facing app is running and still has `data.json` in memory too.

So we probably need a strategy to have our web server do it as it runs — since it already has the dictionary in memory. Fortunately, we only have one web process, so concurrency isn't an issue.

Rough thought:

- [ ] At startup, start traversing and creating symlinks, in the background and async'ly. As we go, delete entries from the dictionary.

- [ ] Update the code that uses the dictionary to check for the symlink first now, both because that's what we ultimately want it do and to be robust to the entry getting deleted from the dictionary.

- [ ] Perhaps periodically on a timer, flush the updated (trimmer) dictionary to the `data.json` file on disk (overwriting what's there), so that if our web server restarts, it can pick up (roughly) where it left off. This is important since the operation might take a while.

- [ ] Later, we can check and see if the `data.json` file on disk is empty (at least an empty `{}` object). If so, then we know it's safe to remove the dictionary from our code altogether.

**Comment by aseemk** [comment]
Also, the `data.json` file currently is minified — all on one line, with no spaces. That makes it compact, but a pain to work with, e.g. Unix `head` and `tail` don't have any meaning.

Since we're updating the file on disk as we go, we might want to pretty-print the JSON to have each entry on its own line. (A quick test seems like the only way to achieve that is to have *some* indentation also, but we can do 1- or 2-space indentation to still keep it relatively light.)

All this said, I'm actually not sure that flushing the updated dictionary to disk will be feasible either, because `JSON.stringify`'ing it may also consume a lot of memory...

**Comment by aseemk** [comment]
Okay, given the discovery that we're pretty much already out of inode space on our production server, we have to put this on hold until we move all the data off disk to Cloud Files: <https://github.com/zoomhub/zoomhub/issues/63#issuecomment-75446735>.

Maybe we can knock this out as part of the data migration...

**Comment by gasi** [comment]
With #111 finished this has been solved.
