### ISSUE TITLE
Figure out way to have secrets for local dev, testing, CI

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#98]
As we add features, we're likely going to want or need to be able to use some paid resource (e.g. Cloud Files for tile uploads; #60 & #93) for local development and testing too.

This means we need some strategy for sharing secrets securely among each other, without exposing those secrets to the world on GitHub. (Edit: and ideally, those secrets would be shared here on GitHub in version control, not out-of-band like Dropbox.)

We already do this for our deployments via [Ansible Vault](http://docs.ansible.com/playbooks_vault.html), so re-using that could be an option.

Travis has its own support for [encrypted files](http://docs.travis-ci.com/user/encrypting-files/) that can get securely decrypted in CI. We will likely need to make use of this any way we go, e.g. to decrypt an Ansible Vault password file.

Similarly, whichever way we go, we'll need some support for it in our app code. One way is to simply rely on environment variables, as we're already doing, but then we'll need something to set those environment variables locally. [Foreman](https://github.com/strongloop/node-foreman) is a tool that can do that, but it relies on its own `.env` file (which is neither YAML or JSON as Ansible Vault supports), so we'd have to figure out a way to keep that file in sync with whatever is encrypted.

We might have to manually keep encrypted and unencrypted in sync whichever way we go; John Resig has written a post describing how [he achieves this](http://ejohn.org/blog/keeping-passwords-in-source-control/) for JSON configs. The difference with this vs. the Foreman approach is that no change is needed in how the app is run; the app takes care of reading the secrets.

Thoughts welcome.

**Comment by aseemk** [comment]
One downside of Ansible Vault is that it supports only one password across all vault files. And presumably, we'll always have some production secrets we'll want encrypted.

This wouldn't necessarily be a big deal, except that Ansible Vault also asks for a password every time, which is super inconvenient, so I'm tempted to save the password to a file so I can use its `--vault-password-file` option — but it's not great to have the key to production secrets sitting in plaintext on my computer.

(`--vault-password-file` also supports the file being an executable script, which can theoretically be more secure, but I don't know off the top of my head how we'd make it more secure while also convenient.)

**Comment by gasi** [comment]
Closing out old issues. Feel free to reopen if relevant.
